name: dev-ci

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn install
      - name: Build with Astro
        run: yarn run build

      - name: configure gcp credentials
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1043231896197/locations/global/workloadIdentityPools/github-actions-pool/providers/github"
          service_account: "github-actions@the-mee-foundation.iam.gserviceaccount.com"

      - name: deploy to bucket
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          gcloud storage rsync --recursive ./dist gs://mee-foundation-bucket
          gcloud storage objects update --content-type="text/html" --cache-control="public, max-age=60" --content-disposition="" gs://mee-foundation-bucket/*.html
          gcloud compute url-maps invalidate-cdn-cache prod-url-map --project the-mee-foundation --path "/*" --host "mee.foundation" --async 
          gcloud compute url-maps invalidate-cdn-cache prod-url-map --project the-mee-foundation --path "/*" --host "auth.mee.foundation" --async 
